// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: bookmarks.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteBookmark = `-- name: DeleteBookmark :exec
DELETE FROM bookmarks
WHERE user_id = $1 AND video_id = $2
`

type DeleteBookmarkParams struct {
	UserID  uuid.UUID
	VideoID uuid.UUID
}

func (q *Queries) DeleteBookmark(ctx context.Context, arg DeleteBookmarkParams) error {
	_, err := q.db.ExecContext(ctx, deleteBookmark, arg.UserID, arg.VideoID)
	return err
}

const getAllBookmarks = `-- name: GetAllBookmarks :many
SELECT id, created_at, updated_at, user_id, video_id FROM bookmarks
`

func (q *Queries) GetAllBookmarks(ctx context.Context) ([]Bookmark, error) {
	rows, err := q.db.QueryContext(ctx, getAllBookmarks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Bookmark
	for rows.Next() {
		var i Bookmark
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.VideoID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVideoIdsBookmarkedByUser = `-- name: GetVideoIdsBookmarkedByUser :many
SELECT video_id FROM bookmarks
WHERE user_id = $1
`

func (q *Queries) GetVideoIdsBookmarkedByUser(ctx context.Context, userID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, getVideoIdsBookmarkedByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var video_id uuid.UUID
		if err := rows.Scan(&video_id); err != nil {
			return nil, err
		}
		items = append(items, video_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertBookmark = `-- name: InsertBookmark :exec
INSERT INTO bookmarks
  (id, created_at, updated_at, user_id, video_id)
VALUES
  ($1, $2, $3, $4, $5)
`

type InsertBookmarkParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	VideoID   uuid.UUID
}

func (q *Queries) InsertBookmark(ctx context.Context, arg InsertBookmarkParams) error {
	_, err := q.db.ExecContext(ctx, insertBookmark,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.UserID,
		arg.VideoID,
	)
	return err
}
