// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: posts.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getAllPosts = `-- name: GetAllPosts :many
SELECT id, created_at, updated_at, title, image_title, image_url, authors, published_at, description, url, feed_id FROM posts
`

func (q *Queries) GetAllPosts(ctx context.Context) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, getAllPosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.ImageTitle,
			&i.ImageUrl,
			&i.Authors,
			&i.PublishedAt,
			&i.Description,
			&i.Url,
			&i.FeedID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertPost = `-- name: InsertPost :exec
INSERT INTO posts
  (id, created_at, updated_at, title, image_title, image_url, authors, published_at, description, url, feed_id)
VALUES
  ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type InsertPostParams struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Title       string
	ImageTitle  string
	ImageUrl    string
	Authors     string
	PublishedAt time.Time
	Description string
	Url         string
	FeedID      uuid.UUID
}

func (q *Queries) InsertPost(ctx context.Context, arg InsertPostParams) error {
	_, err := q.db.ExecContext(ctx, insertPost,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Title,
		arg.ImageTitle,
		arg.ImageUrl,
		arg.Authors,
		arg.PublishedAt,
		arg.Description,
		arg.Url,
		arg.FeedID,
	)
	return err
}
